name = "IO-Fortran-Library"
version = "1.3.1"
license = "MIT"
author = "Austin C Bullock"
maintainer = "acb.bullock@gmail.com"
copyright = "© 2022, Austin C Bullock"

executable = [
  { name = "benchmark-array", source-dir = "benchmarks", main = "benchmark-array.f90" },
  { name = "benchmark-ints", source-dir = "benchmarks", main = "benchmark-ints.f90" }
]

[build]
auto-executables = false
auto-tests = true
auto-examples = true

[install]
library = true
